### ISSUE TITLE
build error: cannot open source file "libavutil/avconfig.h"

### ISSUE THREAD

**Issue by SileYin** [yaasdf/lunaticvibes#1]
Getting error `cannot open source file "libavutil/avconfig.h"`

Note that in the `.gitignore` file in `ext/FFmpeg/libavutil` Line 1 is `/avconfig.h`

**Comment by wz18207** [comment]
yeah. same with me. i havent seen any documents for debug/release.

**Comment by jbscj** [comment]
You have to configure ffmpeg yourselves. Check INSTALL.md under the repo
