### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by Z-fly** [yaasdf/lunaticvibes#10]
增加更多分辨率支持
例如 1360X768 3440×1440

HI-SPEED 能否自定义？像beatoraja那样
![image](https://user-images.githubusercontent.com/10470892/190836056-735c7e6a-eadf-47ff-9318-f26031ee6ac2.png)

BGA 像lr2那样改size
![image](https://user-images.githubusercontent.com/10470892/190836123-e5ac3ad8-8dfe-4d44-b8da-ed4d6f42bba6.png)

兼容更多格式的bga 像beatoraja那样
看了下，现在应该是支持的，就是更加智能一点，比如同目录下有更高画质的bga文件，优先使用那个文件

兼容更多编码
![image](https://user-images.githubusercontent.com/10470892/190836640-2c2461d9-6d63-42cb-aca1-9feb0d5b80b7.png)

**Comment by yaasdf** [comment]
*增加更多分辨率支持*
全屏模式下显示屏幕支持的所有分辨率

*HI-SPEED 能否自定义？*
ESC菜单->游戏 添加滑条

*BGA size*
done

*兼容更多格式的bga*
#15 

*兼容更多编码*
bms是文本文件，只能通过内容识别编码；目前支持粗识别Shift-JIS, EUC-KR, UTF-8
添加编码会增加识别的复杂度，加上其他编码不被主流播放器支持，这里不作支持
