### ISSUE TITLE
叠加层的问题？

### ISSUE THREAD

**Issue by Z-fly** [yaasdf/lunaticvibes#12]
接#11  不好意思 我再问问
开头的显示不正确吗？

https://user-images.githubusercontent.com/10470892/196193836-7df6e526-ce96-44ae-88b9-88742ffc482d.mp4

**Comment by Z-fly** [comment]
https://cncncloud.com/s/Exjv5t2?path=%2FChronoflasH

**Comment by yaasdf** [comment]
BMS LAYER会把#000000作为透明色处理。
LR2好像读png LAYER的时候是不作透明处理，直接显示；试了一下其他几个实现，都做了透明处理。
我觉得跟随主流好一点。不作修改

- LR2
![LR2 2022-10-27 22-08-28](https://user-images.githubusercontent.com/30231846/198308918-6783b87d-9ea7-436c-bac9-0b1208945e1b.png)

- uBMplay 1.5.2
![Snipaste_2022-10-27_22-11-28](https://user-images.githubusercontent.com/30231846/198308960-31dd59ff-fc3e-4b33-869e-781fc20f2dd0.png)

- mBMplay v2.22.0222.0
![Snipaste_2022-10-27_22-23-23](https://user-images.githubusercontent.com/30231846/198312835-a5c2340f-123f-4f42-b760-c6e663d3f267.png)

- beatoraja 0.8.1
![20221027_221400_Play_LEVEL5 ChronoflasH -Easy-](https://user-images.githubusercontent.com/30231846/198309718-e21e9c7b-bf43-426a-a0e4-cff139a1f8e9.png)

**Comment by Z-fly** [comment]
我以为你可以在设置里加个png LAYER的选项卡
