### ISSUE TITLE
【BUG】切换谱面后 STAGEFILE还是上个谱面的

### ISSUE THREAD

**Issue by Z-fly** [yaasdf/lunaticvibes#13]
1. 复现：自动播放一个谱面，然后按ESC，点击其他谱面
![image](https://user-images.githubusercontent.com/10470892/198861366-7535f4e2-b3af-4ffa-916d-47c7a6470a95.png)
STAGEFILE还是上个谱面的

2. BANNER如果是bmp的话，好像无法自适应缩放？

3. 还有就是HEVC和AV1的解码器好像没加？

**Comment by yaasdf** [comment]
1. done
2. 没有做自适应，都是拉伸
3. #16
