### ISSUE TITLE
any place for discussing development?

### ISSUE THREAD

**Issue by wz18207** [yaasdf/lunaticvibes#2]
yeah Interested in seeing this project. 
however i havent see any place for improving functions or others.
is there any places like discord or other community for discussing development.
maybe i can give some help. etc: iidx gacha ticket or gauge shift in beatoraja etc
thanks!

**Comment by yaasdf** [comment]
因为之前基本上只有我一个人在做，现在还没有专门的讨论群组

**Comment by wz18207** [comment]
OK那么能不能类似有个todolist的东西，我手上有些东西可以分享给你希望能对develop有帮助，遗憾的是目前来说我并没有充足的时间

**Comment by yaasdf** [comment]
没有明确的todolist。。看到缺什么做什么😅😅
