### ISSUE TITLE
Add Main BPM Fix

### ISSUE THREAD

**Issue by marysiamzawka** [yaasdf/lunaticvibes#20]
Similar to [beatoraja's MainBPM](https://github.com/exch-bms2/beatoraja/commit/99bf2d4d5e4b671747cb8c6a1b2f2afa73a174f2), being able to set the HSFIX to Main BPM (=where most density happens) would be nice.

**Comment by yaasdf** [comment]
https://github.com/yaasdf/lunaticvibes/releases/tag/0.10.3
