### ISSUE TITLE
Arena rival's lamp always returned as Easy Clear

### ISSUE THREAD

**Issue by marysiamzawka** [yaasdf/lunaticvibes#25]
Tonight I was testing ARENA MODE with a friend.
We were both playing with RANDOM and the same gauge.

**Expected behaviour**
We would see each other's clear lamps properly on the Result screen

**Actual behaviour**
Rival's lamp was always returned as E-CLEAR

| Host | Rival |
|------|-------|
| ![obraz](https://user-images.githubusercontent.com/20336327/209726217-3da0ea83-e672-46e6-a1b6-3ffc61bf333a.png)   | ![obraz](https://user-images.githubusercontent.com/20336327/209726231-b0fa4a07-e7af-4b79-ac2d-26413aca3bb8.png)    |
| ![obraz](https://user-images.githubusercontent.com/20336327/209726269-4edee075-1e60-48b8-b989-8995294fc839.png)   | ![obraz](https://user-images.githubusercontent.com/20336327/209726282-61bc1221-0be6-41c3-a63f-ab4b3905e8c3.png)    |
| ![obraz](https://user-images.githubusercontent.com/20336327/209726308-99efb241-8b36-4f77-980a-f7b5be95ae95.png)   | ![obraz](https://user-images.githubusercontent.com/20336327/209726320-5b32089f-2164-49a5-968c-f5f36eb6534d.png)    |

**Comment by yaasdf** [comment]
Both the program and the skin patch are problematic. Fixed in [0.10.2](https://github.com/yaasdf/lunaticvibes/releases/tag/0.10.2)
