### ISSUE TITLE
问题：右alt不能用于设置键位（还有一些建议）

### ISSUE THREAD

**Issue by MiyakoMeow** [yaasdf/lunaticvibes#5]
1、右alt不能用于设置键位，已排除输入法原因
2、扫盘速度和LR2一样慢，并且扫盘的时候cpu和硬盘都没跑满，可以考虑一下用一条线程读取bms文件，读取文件后把文件内容和解析任务交给别的线程
3、DP铺面解析没做好，只有白键
4、选歌界面的上下切换速度可以做得快一点

**Comment by AFLeartLey** [comment]
dp我这里是没问题的 可能皮肤和/或谱面问题

**Comment by MiyakoMeow** [comment]
应该是皮肤问题，我之前直接把我的LR2里的那个LR2files文件夹复制过来，结果DP下蓝键和combo显示出锅了
然后重新安装后把hakula那个LR2files复制过来再用，就没问题了

**Comment by yaasdf** [comment]
1. 加了
2. 因为就是很慢。deal with it
3. 请问是哪个皮肤
4. F9->Advanced能调速度

**Comment by yaasdf** [comment]
Closing as no response received from the author.
