### ISSUE TITLE
部分皮肤设定在SkinSelect界面更改后未生效

### ISSUE THREAD

**Issue by Sonic-TV** [yaasdf/lunaticvibes#9]
需要更改对应皮肤设定的yml文件才可以生效，原因不明

**Comment by yaasdf** [comment]
什么皮肤

**Comment by yaasdf** [comment]
Got direct contact with the author.
Fixed with https://github.com/yaasdf/lunaticvibes/commit/56a8dca99a1151e38a72b1376ada528901f52cb0
